=== uwscope/scope-web/scope_shared/scope/schemas/documents/safety-plan.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://uwscope.org/schemas/documents/safety-plan",
	"title": "ISafetyPlan",
	"description": "ISafetyPlan Type",
	"type": "object",
	"properties": {
		"_id": {
			"type": "string"
		},
		"_type": {
			"const": "safetyPlan"
		},
		"_rev": {
			"type": "number"
		},
		"assigned": {
			"type": "boolean"
		},
		"assignedDateTime": {
			"$ref": "/schemas/utils/datetime#/properties/datetime"
		},
		"lastUpdatedDateTime": {
			"$ref": "/schemas/utils/datetime#/properties/datetime"
		},
		"reasonsForLiving": {
			"type": "string"
		},
		"warningSigns": {
			"type": "array",
			"items": { "type": "string" }
		},
		"copingStrategies": {
			"type": "array",
			"items": { "type": "string" }
		},
		"socialDistractions": {
			"type": "array",
			"items": {
				"$ref": "/schemas/documents/utils/contact"
			}
		},
		"settingDistractions": {
			"type": "array",
			"items": { "type": "string" }
		},
		"supporters": {
			"type": "array",
			"items": {
				"$ref": "/schemas/documents/utils/contact"
			}
		},
		"professionals": {
			"type": "array",
			"items": {
				"$ref": "/schemas/documents/utils/contact"
			}
		},
		"urgentServices": {
			"type": "array",
			"items": {
				"$ref": "/schemas/documents/utils/contact"
			}
		},
		"safeEnvironment": {
			"type": "array",
			"items": { "type": "string" }
		}
	},
	"additionalProperties": false,
	"required": ["_type", "assigned", "assignedDateTime"]
}

=== uwscope/scope-web/scope_shared/scope/testing/test_schemas/json/safety-plan/valid/distractions-string-array.json
{
    "_type": "safetyPlan",
    "_rev": 1,
    "assigned": true,
	"assignedDateTime": "2010-01-01T11:11:11Z",
    "reasonsForLiving": "To stare at Mt. Rainier.",
    "settingDistractions": ["Love watching TV.", "Love watching Ted Lasso."],
    "supporters": [
        {
            "name": "Name",
            "address": "Address",
            "phoneNumber": "Number"
        }
    ]
}
