=== uwscope/scope-web/scope_shared/scope/schemas/documents/values-inventory.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://uwscope.org/schemas/documents/values-inventory",
	"title": "IValuesInventory",
	"description": "IValuesInventory Type",
	"type": "object",
	"properties": {
		"_id": {
			"type": "string"
		},
		"_type": {
			"const": "valuesInventory"
		},
		"_rev": {
			"type": "number"
		},
		"assigned": {
			"type": "boolean"
		},
		"assignedDateTime": {
			"$ref": "/schemas/utils/datetime#/properties/datetime"
		},
		"lastUpdatedDateTime": {
			"$ref": "/schemas/utils/datetime#/properties/datetime"
		},
		"values": {
			"type": "array",
			"items": {
				"$ref": "/schemas/documents/utils/life-area-value"
			}
		}
	},
	"additionalProperties": false,
	"required": ["_type", "assigned", "assignedDateTime"]
}

=== uwscope/scope-web/scope_shared/scope/testing/test_schemas/json/values-inventory.json
{
    "_type": "valuesInventory",
    "_rev": 1,
    "assigned": true,
    "assignedDateTime": "2012-12-12T12:12:12Z",
    "values": [
        {
            "name": "name",
            "createdDateTime": "2012-12-12T12:12:12Z",
            "editedDateTime": "2012-12-12T12:12:12Z",
            "lifeareaId": "",
            "activities": [
                {
                    "name": "name",
                    "createdDateTime": "2012-12-12T12:12:12Z",
                    "editedDateTime": "2012-12-12T12:12:12Z",
                    "enjoyment": 5,
                    "importance": 5
                }
            ]
        }
    ]
}
