=== uwscope/scope-web/scope_shared/scope/schemas/clinical-history.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://uwscope.org/schemas/clinical-history",
	"title": "IClinicalHistory",
	"description": "IClinicalHistory Type",
	"type": "object",
	"properties": {
		"_type": { "const": "clinicalHistory" },
		"_rev": { "type": "number" },
		"primaryCancerDiagnosis": {
			"type": "string"
		},
		"dateOfCancerDiagnosis": {
			"$ref": "/schemas/regexes#/properties/dateOfCancerDiagnosis"
		},
		"currentTreatmentRegimen": {
			"$ref": "/schemas/enums#/properties/cancerTreatmentRegimenFlags"
		},
		"currentTreatmentRegimenOther": {
			"type": "string"
		},
		"currentTreatmentRegimenNotes": {
			"type": "string"
		},
		"psychDiagnosis": {
			"type": "string"
		},
		"pastPsychHistory": {
			"type": "string"
		},
		"pastSubstanceUse": {
			"type": "string"
		},
		"psychSocialBackground": {
			"type": "string"
		}
	},
	"additionalProperties": false,
	"$comment": "None of the fields are required.",
	"required": ["_type"]
}

=== uwscope/scope-web/scope_shared/scope/testing/test_schemas/json/clinical-history.json
{
	"_type": "clinicalHistory",
	"_rev": 1,
	"primaryCancerDiagnosis": "primaryCancerDiagnosis",
	"dateOfCancerDiagnosis": "2012-10-23",
	"currentTreatmentRegimen": {
		"Surgery": true,
		"Chemotherapy": true,
		"Radiation": true,
		"Stem Cell Transplant": true,
		"Immunotherapy": true,
		"CAR-T": true,
		"Endocrine": true,
		"Surveillance": true
	},
	"currentTreatmentRegimenOther": "currentTreatmentRegimenOther",
	"currentTreatmentRegimenNotes": "currentTreatmentRegimenNotes",
	"psychDiagnosis": "psychDiagnosis",
	"pastPsychHistory": "pastPsychHistory",
	"pastSubstanceUse": "pastSubstanceUse",
	"psychSocialBackground": "psychSocialBackground"
}
