=== uwscope/scope-web/scope_shared/scope/schemas/config/assessment-content.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://uwscope.org/schemas/config/assessment-content",
	"title": "IAssessmentContent",
	"type": "object",
	"properties": {
		"id": {
			"type": "string"
		},
		"name": { "type": "string" },
		"instruction": { "type": "string" },
		"questions": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"question": { "type": "string" },
					"id": { "type": "string" }
				},
				"additionalProperties": false,
				"required": ["question", "id"]
			}
		},
		"options": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"text": { "type": "string" },
					"value": { "type": "number" }
				},
				"additionalProperties": false,
				"required": ["text", "value"]
			}
		},
		"interpretationName": { "type": "string" },
		"interpretationTable": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"score": { "type": "string" },
					"max": { "type": "number" },
					"interpretation": { "type": "string" }
				},
				"additionalProperties": false,
				"required": ["score", "max", "interpretation"]
			},
			"minItems": 0
		}
	},
	"additionalProperties": false,
	"required": ["id", "name", "questions", "options"]
}

=== uwscope/scope-web/server_flask/app_config/assessments/medication.json
{
	"id": "medication",
	"name": "Medication",
	"instruction": "The following questions pertain to any medications you are taking for stress, mood, anxiety, sleep, or other psychological symptoms.",
	"questions": [
		{
			"question": "In the past 7 days, did you take all your prescribed medications as scheduled?",
			"id": "adherence"
		}
	],
	"options": [
		{
			"text": "Yes, I took my medications as scheduled",
			"value": 1
		},
		{
			"text": "No, I did not take all my medications as scheduled",
			"value": 0
		}
	],
	"interpretationName": "Medication tracking",
	"interpretationTable": []
}

=== uwscope/scope-web/server_flask/app_config/assessments/gad7.json
{
  "id": "gad-7",
  "name": "Anxiety",
  "instruction": "Over the last 2 weeks, how often have you been bothered by any of the following problems?",
  "questions": [
    {
      "question": "Feeling nervous, anxious, or on edge",
      "id": "Anxious"
    },
    {
      "question": "Not being able to stop or control worrying",
      "id": "Constant worrying"
    },
    {
      "question": "Worrying too much about different things",
      "id": "Worrying too much"
    },
    {
      "question": "Trouble relaxing",
      "id": "Trouble relaxing"
    },
    {
      "question": "Being so restless that it is hard to sit still",
      "id": "Restless"
    },
    {
      "question": "Becoming easily annoyed or irritated",
      "id": "Irritable"
    },
    {
      "question": "Feeling afraid as if something awful might happen",
      "id": "Afraid"
    }
  ],
  "options": [
    {
      "text": "Not at all",
      "value": 0
    },
    {
      "text": "Several days",
      "value": 1
    },
    {
      "text": "More than half the days",
      "value": 2
    },
    {
      "text": "Nearly every day",
      "value": 3
    }
  ],
  "interpretationName": "Anxiety severity",
  "interpretationTable": [
    {
      "score": "0-4",
      "max": 4,
      "interpretation": "You have minimal or no symptoms â€“ keep up the good work!"
    },
    {
      "score": "5-9",
      "max": 9,
      "interpretation": "Your symptoms are relatively mild. Keep up the good work as you and your clinical social worker collaborate to decrease them even more!"
    },
    {
      "score": "10-14",
      "max": 14,
      "interpretation": "Your symptoms are in the moderate severity range. Please keep working with your clinical social worker and the rest of your team to help you feel better."
    },
    {
      "score": "15+",
      "max": 27,
      "interpretation": "You still have significant symptoms that could benefit from more treatment. Please keep working with your clinical social worker and the rest of your team to help you feel better."
    }
  ]
}

=== uwscope/scope-web/server_flask/app_config/assessments/phq9.json
{
  "id": "phq-9",
  "name": "Depression",
  "instruction": "Over the last 2 weeks, how often have you been bothered by any of the following problems?",
  "questions": [
    {
      "question": "Little interest or pleasure in doing things",
      "id": "Interest"
    },
    {
      "question": "Feeling down, depressed, or hopeless",
      "id": "Mood"
    },
    {
      "question": "Trouble falling or staying asleep, or sleeping too much",
      "id": "Sleep"
    },
    {
      "question": "Feeling tired or having little energy",
      "id": "Energy"
    },
    {
      "question": "Poor appetite or overeating",
      "id": "Appetite"
    },
    {
      "question": "Feeling bad about yourself or that you are a failure or have let yourself or your family down",
      "id": "Guilt"
    },
    {
      "question": "Trouble concentrating on things, such as reading the newspaper or watching television",
      "id": "Concentrating"
    },
    {
      "question": "Moving or speaking so slowly that other people could have noticed. Or the opposite being so fidgety or restless that you have been moving around a lot more than usual",
      "id": "Motor"
    },
    {
      "question": "Thoughts that you would be better off dead, or of hurting yourself",
      "id": "Suicide"
    }
  ],
  "options": [
    {
      "text": "Not at all",
      "value": 0
    },
    {
      "text": "Several days",
      "value": 1
    },
    {
      "text": "More than half the days",
      "value": 2
    },
    {
      "text": "Nearly every day",
      "value": 3
    }
  ],
  "interpretationName": "Depression severity",
  "interpretationTable": [
    {
      "score": "0-4",
      "max": 4,
      "interpretation": "You have minimal or no symptoms â€“ keep up the good work!"
    },
    {
      "score": "5-9",
      "max": 9,
      "interpretation": "Your symptoms are relatively mild. Keep up the good work as you and your clinical social worker collaborate to decrease them even more!"
    },
    {
      "score": "10-14",
      "max": 14,
      "interpretation": "Your symptoms are in the moderate severity range. Please keep working with your clinical social worker and the rest of your team to help you feel better."
    },
    {
      "score": "15+",
      "max": 27,
      "interpretation": "You still have significant symptoms that could benefit from more treatment. Please keep working with your clinical social worker and the rest of your team to help you feel better."
    }
  ]
}
